import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleDollarSign, FileSearch, MapPinned, Search, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/dashboard-shell";

const icons = { search: Search, map: MapPinned, cost: CircleDollarSign, file: FileSearch };

export function FoundationPage({ type, eyebrow, title, description }: { type: keyof typeof icons; eyebrow: string; title: string; description: string }) {
  const Icon = icons[type];
  return <div><PageIntro eyebrow={eyebrow} title={title} description={description} /><section className="grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-[1.5rem] border border-[#dce5e3] bg-white p-6 sm:p-8"><div className="flex size-14 items-center justify-center rounded-2xl bg-[#e8f4e8] text-[#4e805e]"><Icon size={25} /></div><h3 className="mt-6 text-2xl font-semibold tracking-[-0.04em]">This workspace is ready</h3><p className="mt-2 max-w-xl text-sm leading-6 text-[#71827e]">The interface is in place. Verified data connections and workflow logic will be added in a later phase.</p><div className="mt-7 space-y-3"><div className="flex items-center gap-3 rounded-xl bg-[#f6faf5] p-3 text-sm text-[#547269]"><CheckCircle2 className="text-[#6b9d76]" size={18} /> Responsive navigation is configured</div><div className="flex items-center gap-3 rounded-xl bg-[#f6faf5] p-3 text-sm text-[#547269]"><CheckCircle2 className="text-[#6b9d76]" size={18} /> No synthetic medical or hospital data</div><div className="flex items-center gap-3 rounded-xl bg-[#f6faf5] p-3 text-sm text-[#547269]"><CheckCircle2 className="text-[#6b9d76]" size={18} /> Ready for the next implementation phase</div></div></div><aside className="rounded-[1.5rem] border border-dashed border-[#b9cfbf] bg-[#f8fbf7] p-6 sm:p-8"><ShieldCheck className="text-[#5f9271]" size={23} /><h3 className="mt-5 text-xl font-semibold tracking-[-0.03em]">Trust comes first</h3><p className="mt-2 text-sm leading-6 text-[#71827e]">CareMatch AI will clearly separate verified information from user-provided context and future demo content.</p><Link href="/" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#356d50]">Back to overview <ArrowRight size={16} /></Link></aside></section></div>;
}
